# Application url
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# browser
browser = chrome

# Credential
username = admin
password = admin@123

# ImplicitWait (In seconds)
ImplicitWait = 10

# ExplicitWait (In seconds)
ExplicitWait = 30

